//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: battle.proto
// Note: requires additional types generated from: serverbase.proto
namespace com.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MBattle")]
  public partial class MBattle : global::ProtoBuf.IExtensible
  {
    public MBattle() {}
    
    private com.protobuf.MBattleTeam _teamA = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"teamA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MBattleTeam teamA
    {
      get { return _teamA; }
      set { _teamA = value; }
    }
    private com.protobuf.MBattleTeam _teamB = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"teamB", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MBattleTeam teamB
    {
      get { return _teamB; }
      set { _teamB = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MAttack> _attackList = new global::System.Collections.Generic.List<com.protobuf.MAttack>();
    [global::ProtoBuf.ProtoMember(4, Name=@"attackList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MAttack> attackList
    {
      get { return _attackList; }
    }
  
    private int _auto = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"auto", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int auto
    {
      get { return _auto; }
      set { _auto = value; }
    }
    private long _nextAttackId = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"nextAttackId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long nextAttackId
    {
      get { return _nextAttackId; }
      set { _nextAttackId = value; }
    }
    private int _subType = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"subType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int subType
    {
      get { return _subType; }
      set { _subType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MBattleTeam")]
  public partial class MBattleTeam : global::ProtoBuf.IExtensible
  {
    public MBattleTeam() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MSpirit> _spiritList = new global::System.Collections.Generic.List<com.protobuf.MSpirit>();
    [global::ProtoBuf.ProtoMember(1, Name=@"spiritList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSpirit> spiritList
    {
      get { return _spiritList; }
    }
  
    private int _strength = (int)-1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private long _bossId = (long)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bossId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long bossId
    {
      get { return _bossId; }
      set { _bossId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MAttack")]
  public partial class MAttack : global::ProtoBuf.IExtensible
  {
    public MAttack() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MSpiritBuff> _remove_buff_before_attack = new global::System.Collections.Generic.List<com.protobuf.MSpiritBuff>();
    [global::ProtoBuf.ProtoMember(1, Name=@"remove_buff_before_attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSpiritBuff> remove_buff_before_attack
    {
      get { return _remove_buff_before_attack; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MSpiritBuff> _add_buff_before_attack = new global::System.Collections.Generic.List<com.protobuf.MSpiritBuff>();
    [global::ProtoBuf.ProtoMember(2, Name=@"add_buff_before_attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSpiritBuff> add_buff_before_attack
    {
      get { return _add_buff_before_attack; }
    }
  
    private long _attackId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"attackId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long attackId
    {
      get { return _attackId; }
      set { _attackId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MTarget> _targets = new global::System.Collections.Generic.List<com.protobuf.MTarget>();
    [global::ProtoBuf.ProtoMember(4, Name=@"targets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MTarget> targets
    {
      get { return _targets; }
    }
  
    private int _turn = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"turn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int turn
    {
      get { return _turn; }
      set { _turn = value; }
    }
    private long _combAttackId = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"combAttackId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long combAttackId
    {
      get { return _combAttackId; }
      set { _combAttackId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MSpiritBuff> _remove_buff_after_attack = new global::System.Collections.Generic.List<com.protobuf.MSpiritBuff>();
    [global::ProtoBuf.ProtoMember(7, Name=@"remove_buff_after_attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSpiritBuff> remove_buff_after_attack
    {
      get { return _remove_buff_after_attack; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MSpiritBuff> _add_buff_after_attack = new global::System.Collections.Generic.List<com.protobuf.MSpiritBuff>();
    [global::ProtoBuf.ProtoMember(8, Name=@"add_buff_after_attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSpiritBuff> add_buff_after_attack
    {
      get { return _add_buff_after_attack; }
    }
  
    private com.protobuf.MBattleTeam _teamA = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"teamA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MBattleTeam teamA
    {
      get { return _teamA; }
      set { _teamA = value; }
    }
    private com.protobuf.MBattleTeam _teamB = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"teamB", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MBattleTeam teamB
    {
      get { return _teamB; }
      set { _teamB = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MTarget")]
  public partial class MTarget : global::ProtoBuf.IExtensible
  {
    public MTarget() {}
    
    private int _skillId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MSpirit> _targets = new global::System.Collections.Generic.List<com.protobuf.MSpirit>();
    [global::ProtoBuf.ProtoMember(2, Name=@"targets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSpirit> targets
    {
      get { return _targets; }
    }
  
    private com.protobuf.MSpirit _attack = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MSpirit attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private com.protobuf.MSpirit _combAttack = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"combAttack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MSpirit combAttack
    {
      get { return _combAttack; }
      set { _combAttack = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSpiritBuff")]
  public partial class MSpiritBuff : global::ProtoBuf.IExtensible
  {
    public MSpiritBuff() {}
    
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MBattleBuff> _buffList = new global::System.Collections.Generic.List<com.protobuf.MBattleBuff>();
    [global::ProtoBuf.ProtoMember(11, Name=@"buffList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MBattleBuff> buffList
    {
      get { return _buffList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSkillCd")]
  public partial class MSkillCd : global::ProtoBuf.IExtensible
  {
    public MSkillCd() {}
    
    private int _skillId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private int _turn = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"turn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int turn
    {
      get { return _turn; }
      set { _turn = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSpirit")]
  public partial class MSpirit : global::ProtoBuf.IExtensible
  {
    public MSpirit() {}
    
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _sysId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sysId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sysId
    {
      get { return _sysId; }
      set { _sysId = value; }
    }
    private int _position = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private long _hp = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private long _hpMax = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hpMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long hpMax
    {
      get { return _hpMax; }
      set { _hpMax = value; }
    }
    private int _angry = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"angry", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int angry
    {
      get { return _angry; }
      set { _angry = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MSkillCd> _skillCd = new global::System.Collections.Generic.List<com.protobuf.MSkillCd>();
    [global::ProtoBuf.ProtoMember(9, Name=@"skillCd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSkillCd> skillCd
    {
      get { return _skillCd; }
    }
  
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _rebound_hp = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"rebound_hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rebound_hp
    {
      get { return _rebound_hp; }
      set { _rebound_hp = value; }
    }
    private int _xi_shang_hp = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"xi_shang_hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xi_shang_hp
    {
      get { return _xi_shang_hp; }
      set { _xi_shang_hp = value; }
    }
    private int _attack_hp = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"attack_hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attack_hp
    {
      get { return _attack_hp; }
      set { _attack_hp = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MSpiritBuff> _add_buff_before_attack = new global::System.Collections.Generic.List<com.protobuf.MSpiritBuff>();
    [global::ProtoBuf.ProtoMember(17, Name=@"add_buff_before_attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSpiritBuff> add_buff_before_attack
    {
      get { return _add_buff_before_attack; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MSpiritBuff> _add_buff_after_attack = new global::System.Collections.Generic.List<com.protobuf.MSpiritBuff>();
    [global::ProtoBuf.ProtoMember(18, Name=@"add_buff_after_attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSpiritBuff> add_buff_after_attack
    {
      get { return _add_buff_after_attack; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _be_skill_before_be_attack = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(19, Name=@"be_skill_before_be_attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> be_skill_before_be_attack
    {
      get { return _be_skill_before_be_attack; }
    }
  
    private int _fashionId = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"fashionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fashionId
    {
      get { return _fashionId; }
      set { _fashionId = value; }
    }
    private int _weaponId = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"weaponId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int weaponId
    {
      get { return _weaponId; }
      set { _weaponId = value; }
    }
    private int _wingId = default(int);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"wingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int wingId
    {
      get { return _wingId; }
      set { _wingId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MBattleBuff> _currentBuff = new global::System.Collections.Generic.List<com.protobuf.MBattleBuff>();
    [global::ProtoBuf.ProtoMember(23, Name=@"currentBuff", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MBattleBuff> currentBuff
    {
      get { return _currentBuff; }
    }
  
    private int _comb_rebound_hp = default(int);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"comb_rebound_hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int comb_rebound_hp
    {
      get { return _comb_rebound_hp; }
      set { _comb_rebound_hp = value; }
    }
    private int _xiXue = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"xiXue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xiXue
    {
      get { return _xiXue; }
      set { _xiXue = value; }
    }
    private int _appearType = default(int);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"appearType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int appearType
    {
      get { return _appearType; }
      set { _appearType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MBattleBuff")]
  public partial class MBattleBuff : global::ProtoBuf.IExtensible
  {
    public MBattleBuff() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _buffId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buffId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buffId
    {
      get { return _buffId; }
      set { _buffId = value; }
    }
    private int _hp = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _hpMax = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hpMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hpMax
    {
      get { return _hpMax; }
      set { _hpMax = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MBattleResult")]
  public partial class MBattleResult : global::ProtoBuf.IExtensible
  {
    public MBattleResult() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MReward> _rewardList = new global::System.Collections.Generic.List<com.protobuf.MReward>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rewardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MReward> rewardList
    {
      get { return _rewardList; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MReward> _starReward = new global::System.Collections.Generic.List<com.protobuf.MReward>();
    [global::ProtoBuf.ProtoMember(3, Name=@"starReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MReward> starReward
    {
      get { return _starReward; }
    }
  
    private int _star = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }
    private int _nextWave = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"nextWave", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nextWave
    {
      get { return _nextWave; }
      set { _nextWave = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_11_1_")]
  public partial class Msg_11_1_ : global::ProtoBuf.IExtensible
  {
    public Msg_11_1_() {}
    
    private com.protobuf.MBattle _battle = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"battle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MBattle battle
    {
      get { return _battle; }
      set { _battle = value; }
    }
    private com.protobuf.MBattleResult _battleResult = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"battleResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MBattleResult battleResult
    {
      get { return _battleResult; }
      set { _battleResult = value; }
    }
    private int _onlyResult = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"onlyResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int onlyResult
    {
      get { return _onlyResult; }
      set { _onlyResult = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_11_2_")]
  public partial class Msg_11_2_ : global::ProtoBuf.IExtensible
  {
    public Msg_11_2_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MAttack> _attackList = new global::System.Collections.Generic.List<com.protobuf.MAttack>();
    [global::ProtoBuf.ProtoMember(1, Name=@"attackList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MAttack> attackList
    {
      get { return _attackList; }
    }
  
    private com.protobuf.MBattleResult _battleResult = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"battleResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MBattleResult battleResult
    {
      get { return _battleResult; }
      set { _battleResult = value; }
    }
    private long _nextAttackId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nextAttackId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long nextAttackId
    {
      get { return _nextAttackId; }
      set { _nextAttackId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_11_3")]
  public partial class Msg_11_3 : global::ProtoBuf.IExtensible
  {
    public Msg_11_3() {}
    
    private long _battleFileId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"battleFileId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long battleFileId
    {
      get { return _battleFileId; }
      set { _battleFileId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_11_3_")]
  public partial class Msg_11_3_ : global::ProtoBuf.IExtensible
  {
    public Msg_11_3_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MBattle> _battle = new global::System.Collections.Generic.List<com.protobuf.MBattle>();
    [global::ProtoBuf.ProtoMember(1, Name=@"battle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MBattle> battle
    {
      get { return _battle; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_11_4")]
  public partial class Msg_11_4 : global::ProtoBuf.IExtensible
  {
    public Msg_11_4() {}
    
    private int _skillId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_11_4_")]
  public partial class Msg_11_4_ : global::ProtoBuf.IExtensible
  {
    public Msg_11_4_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_11_5")]
  public partial class Msg_11_5 : global::ProtoBuf.IExtensible
  {
    public Msg_11_5() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_11_5_")]
  public partial class Msg_11_5_ : global::ProtoBuf.IExtensible
  {
    public Msg_11_5_() {}
    
    private int _auto = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"auto", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int auto
    {
      get { return _auto; }
      set { _auto = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_11_6")]
  public partial class Msg_11_6 : global::ProtoBuf.IExtensible
  {
    public Msg_11_6() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_11_6_")]
  public partial class Msg_11_6_ : global::ProtoBuf.IExtensible
  {
    public Msg_11_6_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_11_7")]
  public partial class Msg_11_7 : global::ProtoBuf.IExtensible
  {
    public Msg_11_7() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}