//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: command.proto
// Note: requires additional types generated from: serverbase.proto
namespace com.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_1_1")]
  public partial class Msg_1_1 : global::ProtoBuf.IExtensible
  {
    public Msg_1_1() {}
    
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private long _targetId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private int _number = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_1_1_")]
  public partial class Msg_1_1_ : global::ProtoBuf.IExtensible
  {
    public Msg_1_1_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MGeneralData")]
  public partial class MGeneralData : global::ProtoBuf.IExtensible
  {
    public MGeneralData() {}
    
    private int _sysId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sysId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sysId
    {
      get { return _sysId; }
      set { _sysId = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _position = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _skillList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"skillList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> skillList
    {
      get { return _skillList; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MBasicAttr> _attrList = new global::System.Collections.Generic.List<com.protobuf.MBasicAttr>();
    [global::ProtoBuf.ProtoMember(5, Name=@"attrList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MBasicAttr> attrList
    {
      get { return _attrList; }
    }
  
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_1_2")]
  public partial class Msg_1_2 : global::ProtoBuf.IExtensible
  {
    public Msg_1_2() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MGeneralData> _left = new global::System.Collections.Generic.List<com.protobuf.MGeneralData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"left", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MGeneralData> left
    {
      get { return _left; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MGeneralData> _right = new global::System.Collections.Generic.List<com.protobuf.MGeneralData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"right", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MGeneralData> right
    {
      get { return _right; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_1_2_")]
  public partial class Msg_1_2_ : global::ProtoBuf.IExtensible
  {
    public Msg_1_2_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MDairyActivity")]
  public partial class MDairyActivity : global::ProtoBuf.IExtensible
  {
    public MDairyActivity() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _day = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"day", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string day
    {
      get { return _day; }
      set { _day = value; }
    }
    private string _startTime = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private string _endTime = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_1_3_")]
  public partial class Msg_1_3_ : global::ProtoBuf.IExtensible
  {
    public Msg_1_3_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MDairyActivity> _activityList = new global::System.Collections.Generic.List<com.protobuf.MDairyActivity>();
    [global::ProtoBuf.ProtoMember(1, Name=@"activityList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MDairyActivity> activityList
    {
      get { return _activityList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_1_4")]
  public partial class Msg_1_4 : global::ProtoBuf.IExtensible
  {
    public Msg_1_4() {}
    
    private string _startTime = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_1_5")]
  public partial class Msg_1_5 : global::ProtoBuf.IExtensible
  {
    public Msg_1_5() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _startTime = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private string _endTime = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_1_6")]
  public partial class Msg_1_6 : global::ProtoBuf.IExtensible
  {
    public Msg_1_6() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _startTime = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private string _endTime = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private int _openActive = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"openActive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int openActive
    {
      get { return _openActive; }
      set { _openActive = value; }
    }
    private string _beginDrawTime = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"beginDrawTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string beginDrawTime
    {
      get { return _beginDrawTime; }
      set { _beginDrawTime = value; }
    }
    private string _endDrawTime = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"endDrawTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string endDrawTime
    {
      get { return _endDrawTime; }
      set { _endDrawTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_1_7")]
  public partial class Msg_1_7 : global::ProtoBuf.IExtensible
  {
    public Msg_1_7() {}
    
    private string _serverTime = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"serverTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string serverTime
    {
      get { return _serverTime; }
      set { _serverTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}