//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: fuben.proto
// Note: requires additional types generated from: serverbase.proto
namespace com.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MWipeResult")]
  public partial class MWipeResult : global::ProtoBuf.IExtensible
  {
    public MWipeResult() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MReward> _rewardList = new global::System.Collections.Generic.List<com.protobuf.MReward>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rewardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MReward> rewardList
    {
      get { return _rewardList; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MReward> _starReward = new global::System.Collections.Generic.List<com.protobuf.MReward>();
    [global::ProtoBuf.ProtoMember(2, Name=@"starReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MReward> starReward
    {
      get { return _starReward; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MFuben")]
  public partial class MFuben : global::ProtoBuf.IExtensible
  {
    public MFuben() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _attackCount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"attackCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attackCount
    {
      get { return _attackCount; }
      set { _attackCount = value; }
    }
    private int _star = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }
    private int _buyAttackCount = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"buyAttackCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buyAttackCount
    {
      get { return _buyAttackCount; }
      set { _buyAttackCount = value; }
    }
    private int _extendStatus = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"extendStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int extendStatus
    {
      get { return _extendStatus; }
      set { _extendStatus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_1_")]
  public partial class Msg_12_1_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_1_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MFuben> _fuben = new global::System.Collections.Generic.List<com.protobuf.MFuben>();
    [global::ProtoBuf.ProtoMember(1, Name=@"fuben", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MFuben> fuben
    {
      get { return _fuben; }
    }
  
    private int _fubenEvent = (int)-1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fubenEvent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int fubenEvent
    {
      get { return _fubenEvent; }
      set { _fubenEvent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_2")]
  public partial class Msg_12_2 : global::ProtoBuf.IExtensible
  {
    public Msg_12_2() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_2_")]
  public partial class Msg_12_2_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_2_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MReward> _rewardList = new global::System.Collections.Generic.List<com.protobuf.MReward>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rewardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MReward> rewardList
    {
      get { return _rewardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_3")]
  public partial class Msg_12_3 : global::ProtoBuf.IExtensible
  {
    public Msg_12_3() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _count = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_3_")]
  public partial class Msg_12_3_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_3_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_4")]
  public partial class Msg_12_4 : global::ProtoBuf.IExtensible
  {
    public Msg_12_4() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_4_")]
  public partial class Msg_12_4_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_4_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_5")]
  public partial class Msg_12_5 : global::ProtoBuf.IExtensible
  {
    public Msg_12_5() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _count = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_5_")]
  public partial class Msg_12_5_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_5_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MWipeResult> _resultList = new global::System.Collections.Generic.List<com.protobuf.MWipeResult>();
    [global::ProtoBuf.ProtoMember(1, Name=@"resultList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MWipeResult> resultList
    {
      get { return _resultList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}