//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: gang.proto
namespace com.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MGang")]
  public partial class MGang : global::ProtoBuf.IExtensible
  {
    public MGang() {}
    
    private long _gangId = (long)-1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gangId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long gangId
    {
      get { return _gangId; }
      set { _gangId = value; }
    }
    private string _gangName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gangName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gangName
    {
      get { return _gangName; }
      set { _gangName = value; }
    }
    private int _level = (int)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _owner = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"owner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string owner
    {
      get { return _owner; }
      set { _owner = value; }
    }
    private string _aim = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"aim", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string aim
    {
      get { return _aim; }
      set { _aim = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MGangMember> _members = new global::System.Collections.Generic.List<com.protobuf.MGangMember>();
    [global::ProtoBuf.ProtoMember(6, Name=@"members", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MGangMember> members
    {
      get { return _members; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MGangMember> _applyMembers = new global::System.Collections.Generic.List<com.protobuf.MGangMember>();
    [global::ProtoBuf.ProtoMember(7, Name=@"applyMembers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MGangMember> applyMembers
    {
      get { return _applyMembers; }
    }
  
    private int _rank = (int)-1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private int _memberCount = (int)-1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"memberCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int memberCount
    {
      get { return _memberCount; }
      set { _memberCount = value; }
    }
    private int _exp = (int)-1;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _applyed = (int)-1;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"applyed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int applyed
    {
      get { return _applyed; }
      set { _applyed = value; }
    }
    private int _ownerSysId = (int)-1;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"ownerSysId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int ownerSysId
    {
      get { return _ownerSysId; }
      set { _ownerSysId = value; }
    }
    private long _totalStrength = (long)-1;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"totalStrength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long totalStrength
    {
      get { return _totalStrength; }
      set { _totalStrength = value; }
    }
    private long _ownerId = (long)-1;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"ownerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long ownerId
    {
      get { return _ownerId; }
      set { _ownerId = value; }
    }
    private int _hasApply = (int)-1;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"hasApply", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int hasApply
    {
      get { return _hasApply; }
      set { _hasApply = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MGangMember")]
  public partial class MGangMember : global::ProtoBuf.IExtensible
  {
    public MGangMember() {}
    
    private long _roleId = (long)-1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _duty = (int)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"duty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int duty
    {
      get { return _duty; }
      set { _duty = value; }
    }
    private int _level = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _online = (int)-1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int online
    {
      get { return _online; }
      set { _online = value; }
    }
    private int _strength = (int)-1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private int _curGangXian = (int)-1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"curGangXian", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int curGangXian
    {
      get { return _curGangXian; }
      set { _curGangXian = value; }
    }
    private int _totalGangXian = (int)-1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"totalGangXian", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int totalGangXian
    {
      get { return _totalGangXian; }
      set { _totalGangXian = value; }
    }
    private int _sex = (int)-1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _job = (int)-1;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int job
    {
      get { return _job; }
      set { _job = value; }
    }
    private int _systemId = (int)-1;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"systemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int systemId
    {
      get { return _systemId; }
      set { _systemId = value; }
    }
    private int _vip = (int)-1;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private int _friend = (int)-1;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"friend", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int friend
    {
      get { return _friend; }
      set { _friend = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_1")]
  public partial class Msg_24_1 : global::ProtoBuf.IExtensible
  {
    public Msg_24_1() {}
    
    private string _gangName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gangName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gangName
    {
      get { return _gangName; }
      set { _gangName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_1_")]
  public partial class Msg_24_1_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_1_() {}
    
    private com.protobuf.MGang _gang = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MGang gang
    {
      get { return _gang; }
      set { _gang = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_3")]
  public partial class Msg_24_3 : global::ProtoBuf.IExtensible
  {
    public Msg_24_3() {}
    
    private long _gangId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gangId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long gangId
    {
      get { return _gangId; }
      set { _gangId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_3_")]
  public partial class Msg_24_3_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_3_() {}
    
    private com.protobuf.MGang _gang = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MGang gang
    {
      get { return _gang; }
      set { _gang = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_4")]
  public partial class Msg_24_4 : global::ProtoBuf.IExtensible
  {
    public Msg_24_4() {}
    
    private long _targetId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_4_")]
  public partial class Msg_24_4_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_4_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_5")]
  public partial class Msg_24_5 : global::ProtoBuf.IExtensible
  {
    public Msg_24_5() {}
    
    private long _targetId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_5_")]
  public partial class Msg_24_5_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_5_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_6")]
  public partial class Msg_24_6 : global::ProtoBuf.IExtensible
  {
    public Msg_24_6() {}
    
    private long _targetId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private int _duty = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"duty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int duty
    {
      get { return _duty; }
      set { _duty = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_6_")]
  public partial class Msg_24_6_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_6_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_7")]
  public partial class Msg_24_7 : global::ProtoBuf.IExtensible
  {
    public Msg_24_7() {}
    
    private long _targetId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_7_")]
  public partial class Msg_24_7_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_7_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_8")]
  public partial class Msg_24_8 : global::ProtoBuf.IExtensible
  {
    public Msg_24_8() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_8_")]
  public partial class Msg_24_8_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_8_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_9")]
  public partial class Msg_24_9 : global::ProtoBuf.IExtensible
  {
    public Msg_24_9() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_9_")]
  public partial class Msg_24_9_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_9_() {}
    
    private com.protobuf.MGang _gang = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MGang gang
    {
      get { return _gang; }
      set { _gang = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_10")]
  public partial class Msg_24_10 : global::ProtoBuf.IExtensible
  {
    public Msg_24_10() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_10_")]
  public partial class Msg_24_10_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_10_() {}
    
    private com.protobuf.MGang _gang = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MGang gang
    {
      get { return _gang; }
      set { _gang = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_11")]
  public partial class Msg_24_11 : global::ProtoBuf.IExtensible
  {
    public Msg_24_11() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_11_")]
  public partial class Msg_24_11_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_11_() {}
    
    private long _targetId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_12")]
  public partial class Msg_24_12 : global::ProtoBuf.IExtensible
  {
    public Msg_24_12() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_12_")]
  public partial class Msg_24_12_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_12_() {}
    
    private long _targetId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private int _memberCount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"memberCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int memberCount
    {
      get { return _memberCount; }
      set { _memberCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_13")]
  public partial class Msg_24_13 : global::ProtoBuf.IExtensible
  {
    public Msg_24_13() {}
    
    private int _page = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int page
    {
      get { return _page; }
      set { _page = value; }
    }
    private int _pageSize = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pageSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pageSize
    {
      get { return _pageSize; }
      set { _pageSize = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_13_")]
  public partial class Msg_24_13_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_13_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MGang> _gangList = new global::System.Collections.Generic.List<com.protobuf.MGang>();
    [global::ProtoBuf.ProtoMember(1, Name=@"gangList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MGang> gangList
    {
      get { return _gangList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_14")]
  public partial class Msg_24_14 : global::ProtoBuf.IExtensible
  {
    public Msg_24_14() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_14_")]
  public partial class Msg_24_14_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_14_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MGang> _gang = new global::System.Collections.Generic.List<com.protobuf.MGang>();
    [global::ProtoBuf.ProtoMember(1, Name=@"gang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MGang> gang
    {
      get { return _gang; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_15")]
  public partial class Msg_24_15 : global::ProtoBuf.IExtensible
  {
    public Msg_24_15() {}
    
    private string _aim = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"aim", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string aim
    {
      get { return _aim; }
      set { _aim = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_15_")]
  public partial class Msg_24_15_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_15_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_16")]
  public partial class Msg_24_16 : global::ProtoBuf.IExtensible
  {
    public Msg_24_16() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_16_")]
  public partial class Msg_24_16_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_16_() {}
    
    private int _operation = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"operation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int operation
    {
      get { return _operation; }
      set { _operation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_17")]
  public partial class Msg_24_17 : global::ProtoBuf.IExtensible
  {
    public Msg_24_17() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_24_17_")]
  public partial class Msg_24_17_ : global::ProtoBuf.IExtensible
  {
    public Msg_24_17_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}