//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: mapmask.proto
// Note: requires additional types generated from: scene.proto
namespace com.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapMaskData")]
  public partial class MapMaskData : global::ProtoBuf.IExtensible
  {
    public MapMaskData() {}
    
    private int _width = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int width
    {
      get { return _width; }
      set { _width = value; }
    }
    private int _height = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }
    private byte[] _mask = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mask", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] mask
    {
      get { return _mask; }
      set { _mask = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapMaskHeight")]
  public partial class MapMaskHeight : global::ProtoBuf.IExtensible
  {
    public MapMaskHeight() {}
    
    private readonly global::System.Collections.Generic.List<float> _height = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(1, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> height
    {
      get { return _height; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapWalkPath")]
  public partial class MapWalkPath : global::ProtoBuf.IExtensible
  {
    public MapWalkPath() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MLocation> _route = new global::System.Collections.Generic.List<com.protobuf.MLocation>();
    [global::ProtoBuf.ProtoMember(1, Name=@"route", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MLocation> route
    {
      get { return _route; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapJumpNode")]
  public partial class MapJumpNode : global::ProtoBuf.IExtensible
  {
    public MapJumpNode() {}
    
    private com.protobuf.MLocation _triggerTrans = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"triggerTrans", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MLocation triggerTrans
    {
      get { return _triggerTrans; }
      set { _triggerTrans = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MLocation> _rounds = new global::System.Collections.Generic.List<com.protobuf.MLocation>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rounds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MLocation> rounds
    {
      get { return _rounds; }
    }
  
    private com.protobuf.MLocation _targetTrans = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"targetTrans", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MLocation targetTrans
    {
      get { return _targetTrans; }
      set { _targetTrans = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapJumpNodes")]
  public partial class MapJumpNodes : global::ProtoBuf.IExtensible
  {
    public MapJumpNodes() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MapJumpNode> _nodes = new global::System.Collections.Generic.List<com.protobuf.MapJumpNode>();
    [global::ProtoBuf.ProtoMember(1, Name=@"nodes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MapJumpNode> nodes
    {
      get { return _nodes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}