//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: role.proto
// Note: requires additional types generated from: serverbase.proto
// Note: requires additional types generated from: general.proto
namespace com.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MRole")]
  public partial class MRole : global::ProtoBuf.IExtensible
  {
    public MRole() {}
    
    private long _id = (long)-1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _sysId = (int)-1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sysId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int sysId
    {
      get { return _sysId; }
      set { _sysId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _sex = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _online = (int)-1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int online
    {
      get { return _online; }
      set { _online = value; }
    }
    private int _level = (int)-1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _strength = (int)-1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private int _silver = (int)-1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"silver", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int silver
    {
      get { return _silver; }
      set { _silver = value; }
    }
    private int _yuanBao = (int)-1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"yuanBao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int yuanBao
    {
      get { return _yuanBao; }
      set { _yuanBao = value; }
    }
    private int _chargeYuanbao = (int)-1;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"chargeYuanbao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int chargeYuanbao
    {
      get { return _chargeYuanbao; }
      set { _chargeYuanbao = value; }
    }
    private int _tiLi = (int)-1;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"tiLi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int tiLi
    {
      get { return _tiLi; }
      set { _tiLi = value; }
    }
    private int _vipLevel = (int)-1;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"vipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int vipLevel
    {
      get { return _vipLevel; }
      set { _vipLevel = value; }
    }
    private long _createTime = (long)-1;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private int _loginCount = (int)-1;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"loginCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int loginCount
    {
      get { return _loginCount; }
      set { _loginCount = value; }
    }
    private int _zoneId = (int)-1;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"zoneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int zoneId
    {
      get { return _zoneId; }
      set { _zoneId = value; }
    }
    private long _tiLiTime = (long)-1;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"tiLiTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long tiLiTime
    {
      get { return _tiLiTime; }
      set { _tiLiTime = value; }
    }
    private string _openId = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"openId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string openId
    {
      get { return _openId; }
      set { _openId = value; }
    }
    private com.protobuf.MBaseGeneral _baseGeneral = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"baseGeneral", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MBaseGeneral baseGeneral
    {
      get { return _baseGeneral; }
      set { _baseGeneral = value; }
    }
    private long _exp = (long)-1;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _buyTiliCount = (int)-1;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"buyTiliCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int buyTiliCount
    {
      get { return _buyTiliCount; }
      set { _buyTiliCount = value; }
    }
    private int _totalStrength = (int)-1;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"totalStrength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int totalStrength
    {
      get { return _totalStrength; }
      set { _totalStrength = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _equip = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(22, Name=@"equip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> equip
    {
      get { return _equip; }
    }
  
    private int _fubenWipeCount = (int)-1;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"fubenWipeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int fubenWipeCount
    {
      get { return _fubenWipeCount; }
      set { _fubenWipeCount = value; }
    }
    private int _competeOrder = (int)-1;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"competeOrder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int competeOrder
    {
      get { return _competeOrder; }
      set { _competeOrder = value; }
    }
    private int _competeScore = (int)-1;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"competeScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int competeScore
    {
      get { return _competeScore; }
      set { _competeScore = value; }
    }
    private int _competeCount = (int)-1;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"competeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int competeCount
    {
      get { return _competeCount; }
      set { _competeCount = value; }
    }
    private int _buyCompeteCount = (int)-1;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"buyCompeteCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int buyCompeteCount
    {
      get { return _buyCompeteCount; }
      set { _buyCompeteCount = value; }
    }
    private long _competeTime = (long)-1;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"competeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long competeTime
    {
      get { return _competeTime; }
      set { _competeTime = value; }
    }
    private int _fashionId = (int)-1;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"fashionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int fashionId
    {
      get { return _fashionId; }
      set { _fashionId = value; }
    }
    private int _weaponId = (int)-1;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"weaponId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int weaponId
    {
      get { return _weaponId; }
      set { _weaponId = value; }
    }
    private int _wingId = (int)-1;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"wingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int wingId
    {
      get { return _wingId; }
      set { _wingId = value; }
    }
    private int _todayChargeYuanbao = (int)-1;
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"todayChargeYuanbao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int todayChargeYuanbao
    {
      get { return _todayChargeYuanbao; }
      set { _todayChargeYuanbao = value; }
    }
    private int _firstChargeYuanBao = (int)-1;
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"firstChargeYuanBao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int firstChargeYuanBao
    {
      get { return _firstChargeYuanBao; }
      set { _firstChargeYuanBao = value; }
    }
    private long _partnerId = (long)-1;
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"partnerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long partnerId
    {
      get { return _partnerId; }
      set { _partnerId = value; }
    }
    private int _sceneStatus = (int)-1;
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"sceneStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int sceneStatus
    {
      get { return _sceneStatus; }
      set { _sceneStatus = value; }
    }
    private long _gangId = (long)-1;
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"gangId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long gangId
    {
      get { return _gangId; }
      set { _gangId = value; }
    }
    private long _sceneStatusTime = (long)-1;
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"sceneStatusTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long sceneStatusTime
    {
      get { return _sceneStatusTime; }
      set { _sceneStatusTime = value; }
    }
    private int _battleStatus = (int)-1;
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"battleStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int battleStatus
    {
      get { return _battleStatus; }
      set { _battleStatus = value; }
    }
    private int _isDownReward = (int)-1;
    [global::ProtoBuf.ProtoMember(48, IsRequired = false, Name=@"isDownReward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int isDownReward
    {
      get { return _isDownReward; }
      set { _isDownReward = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _skill = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(49, Name=@"skill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> skill
    {
      get { return _skill; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _fettersSkill = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(50, Name=@"fettersSkill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> fettersSkill
    {
      get { return _fettersSkill; }
    }
  
    private int _skillPoints = (int)-1;
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"skillPoints", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int skillPoints
    {
      get { return _skillPoints; }
      set { _skillPoints = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MRoleGeneral")]
  public partial class MRoleGeneral : global::ProtoBuf.IExtensible
  {
    public MRoleGeneral() {}
    
    private long _id = (long)-1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _sysId = (int)-1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sysId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int sysId
    {
      get { return _sysId; }
      set { _sysId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _sex = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _online = (int)-1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int online
    {
      get { return _online; }
      set { _online = value; }
    }
    private int _level = (int)-1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _strength = (int)-1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private com.protobuf.MFightAttr _fightAttr = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"fightAttr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MFightAttr fightAttr
    {
      get { return _fightAttr; }
      set { _fightAttr = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MGeneral> _generalList = new global::System.Collections.Generic.List<com.protobuf.MGeneral>();
    [global::ProtoBuf.ProtoMember(10, Name=@"generalList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MGeneral> generalList
    {
      get { return _generalList; }
    }
  
    private int _totalStrength = (int)-1;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"totalStrength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int totalStrength
    {
      get { return _totalStrength; }
      set { _totalStrength = value; }
    }
    private int _fashionId = (int)-1;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"fashionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int fashionId
    {
      get { return _fashionId; }
      set { _fashionId = value; }
    }
    private int _weaponId = (int)-1;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"weaponId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int weaponId
    {
      get { return _weaponId; }
      set { _weaponId = value; }
    }
    private int _wingId = (int)-1;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"wingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int wingId
    {
      get { return _wingId; }
      set { _wingId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_1_")]
  public partial class Msg_3_1_ : global::ProtoBuf.IExtensible
  {
    public Msg_3_1_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_2_")]
  public partial class Msg_3_2_ : global::ProtoBuf.IExtensible
  {
    public Msg_3_2_() {}
    
    private com.protobuf.MRole _role = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MRole role
    {
      get { return _role; }
      set { _role = value; }
    }
    private long _rewardExp = (long)-1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rewardExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)-1)]
    public long rewardExp
    {
      get { return _rewardExp; }
      set { _rewardExp = value; }
    }
    private int _tip = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int tip
    {
      get { return _tip; }
      set { _tip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_3")]
  public partial class Msg_3_3 : global::ProtoBuf.IExtensible
  {
    public Msg_3_3() {}
    
    private long _targetId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private string _targetName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string targetName
    {
      get { return _targetName; }
      set { _targetName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_3_")]
  public partial class Msg_3_3_ : global::ProtoBuf.IExtensible
  {
    public Msg_3_3_() {}
    
    private com.protobuf.MRoleGeneral _target = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MRoleGeneral target
    {
      get { return _target; }
      set { _target = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_4")]
  public partial class Msg_3_4 : global::ProtoBuf.IExtensible
  {
    public Msg_3_4() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}