//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: account.proto
// Note: requires additional types generated from: role.proto
// Note: requires additional types generated from: card.proto
// Note: requires additional types generated from: fuBen.proto
// Note: requires additional types generated from: bag.proto
// Note: requires additional types generated from: equip.proto
// Note: requires additional types generated from: active.proto
// Note: requires additional types generated from: friend.proto
// Note: requires additional types generated from: task.proto
// Note: requires additional types generated from: object.proto
// Note: requires additional types generated from: pet.proto
// Note: requires additional types generated from: horse.proto
// Note: requires additional types generated from: gang.proto
// Note: requires additional types generated from: lieMing.proto
// Note: requires additional types generated from: battle.proto
// Note: requires additional types generated from: grocery.proto
// Note: requires additional types generated from: goodExchange.proto
// Note: requires additional types generated from: fixedActivity.proto
// Note: requires additional types generated from: qisheng.proto
// Note: requires additional types generated from: tianGong.proto
// Note: requires additional types generated from: signIn.proto
namespace com.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MLoginData")]
  public partial class MLoginData : global::ProtoBuf.IExtensible
  {
    public MLoginData() {}
    
    private com.protobuf.MRole _role = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MRole role
    {
      get { return _role; }
      set { _role = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MCard> _card = new global::System.Collections.Generic.List<com.protobuf.MCard>();
    [global::ProtoBuf.ProtoMember(2, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MCard> card
    {
      get { return _card; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MArea> _areaList = new global::System.Collections.Generic.List<com.protobuf.MArea>();
    [global::ProtoBuf.ProtoMember(3, Name=@"areaList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MArea> areaList
    {
      get { return _areaList; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MCopy> _copyList = new global::System.Collections.Generic.List<com.protobuf.MCopy>();
    [global::ProtoBuf.ProtoMember(4, Name=@"copyList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MCopy> copyList
    {
      get { return _copyList; }
    }
  
    private com.protobuf.MBag _bag = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"bag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MBag bag
    {
      get { return _bag; }
      set { _bag = value; }
    }
    private com.protobuf.MBattleCopy _battleCopy = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"battleCopy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MBattleCopy battleCopy
    {
      get { return _battleCopy; }
      set { _battleCopy = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MEquip> _equip = new global::System.Collections.Generic.List<com.protobuf.MEquip>();
    [global::ProtoBuf.ProtoMember(9, Name=@"equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MEquip> equip
    {
      get { return _equip; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MFriend> _friend = new global::System.Collections.Generic.List<com.protobuf.MFriend>();
    [global::ProtoBuf.ProtoMember(11, Name=@"friend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MFriend> friend
    {
      get { return _friend; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MFriend> _applyFriend = new global::System.Collections.Generic.List<com.protobuf.MFriend>();
    [global::ProtoBuf.ProtoMember(12, Name=@"applyFriend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MFriend> applyFriend
    {
      get { return _applyFriend; }
    }
  
    private int _npcId = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"npcId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int npcId
    {
      get { return _npcId; }
      set { _npcId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MBaiShen> _baiShenList = new global::System.Collections.Generic.List<com.protobuf.MBaiShen>();
    [global::ProtoBuf.ProtoMember(14, Name=@"baiShenList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MBaiShen> baiShenList
    {
      get { return _baiShenList; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MRoleReward> _rewardList = new global::System.Collections.Generic.List<com.protobuf.MRoleReward>();
    [global::ProtoBuf.ProtoMember(15, Name=@"rewardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MRoleReward> rewardList
    {
      get { return _rewardList; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MTask> _taskList = new global::System.Collections.Generic.List<com.protobuf.MTask>();
    [global::ProtoBuf.ProtoMember(16, Name=@"taskList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MTask> taskList
    {
      get { return _taskList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _taskTotalList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(17, Name=@"taskTotalList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> taskTotalList
    {
      get { return _taskTotalList; }
    }
  
    private int _mailNumber = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"mailNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mailNumber
    {
      get { return _mailNumber; }
      set { _mailNumber = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _tiLiRewardList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(19, Name=@"tiLiRewardList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> tiLiRewardList
    {
      get { return _tiLiRewardList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _vipRewardList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(20, Name=@"vipRewardList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> vipRewardList
    {
      get { return _vipRewardList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _levelRewardList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(21, Name=@"levelRewardList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> levelRewardList
    {
      get { return _levelRewardList; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MReward> _loginRewardList = new global::System.Collections.Generic.List<com.protobuf.MReward>();
    [global::ProtoBuf.ProtoMember(22, Name=@"loginRewardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MReward> loginRewardList
    {
      get { return _loginRewardList; }
    }
  
    private int _loginRewardCount = default(int);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"loginRewardCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int loginRewardCount
    {
      get { return _loginRewardCount; }
      set { _loginRewardCount = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _checkInRewardList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(24, Name=@"checkInRewardList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> checkInRewardList
    {
      get { return _checkInRewardList; }
    }
  
    private int _checkInCount = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"checkInCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int checkInCount
    {
      get { return _checkInCount; }
      set { _checkInCount = value; }
    }
    private com.protobuf.MPet _pet = null;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"pet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MPet pet
    {
      get { return _pet; }
      set { _pet = value; }
    }
    private com.protobuf.MHorse _horse = null;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"horse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MHorse horse
    {
      get { return _horse; }
      set { _horse = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MActiveData> _activeData = new global::System.Collections.Generic.List<com.protobuf.MActiveData>();
    [global::ProtoBuf.ProtoMember(28, Name=@"activeData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MActiveData> activeData
    {
      get { return _activeData; }
    }
  
    private int _bossReward = default(int);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"bossReward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bossReward
    {
      get { return _bossReward; }
      set { _bossReward = value; }
    }
    private int _competeReward = default(int);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"competeReward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int competeReward
    {
      get { return _competeReward; }
      set { _competeReward = value; }
    }
    private int _contestReward = default(int);
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"contestReward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int contestReward
    {
      get { return _contestReward; }
      set { _contestReward = value; }
    }
    private com.protobuf.MActiveGiftData _activeGiftData = null;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"activeGiftData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MActiveGiftData activeGiftData
    {
      get { return _activeGiftData; }
      set { _activeGiftData = value; }
    }
    private string _invitedFriend = "";
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"invitedFriend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string invitedFriend
    {
      get { return _invitedFriend; }
      set { _invitedFriend = value; }
    }
    private int _moneyTreeCount = default(int);
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"moneyTreeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int moneyTreeCount
    {
      get { return _moneyTreeCount; }
      set { _moneyTreeCount = value; }
    }
    private long _startServerZeroTime = default(long);
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"startServerZeroTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long startServerZeroTime
    {
      get { return _startServerZeroTime; }
      set { _startServerZeroTime = value; }
    }
    private com.protobuf.MGang _gang = null;
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"gang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MGang gang
    {
      get { return _gang; }
      set { _gang = value; }
    }
    private int _normalCopyId = default(int);
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"normalCopyId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int normalCopyId
    {
      get { return _normalCopyId; }
      set { _normalCopyId = value; }
    }
    private int _eliteCopyId = default(int);
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"eliteCopyId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int eliteCopyId
    {
      get { return _eliteCopyId; }
      set { _eliteCopyId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MActiveAwardData> _mactiveAwardData = new global::System.Collections.Generic.List<com.protobuf.MActiveAwardData>();
    [global::ProtoBuf.ProtoMember(39, Name=@"mactiveAwardData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MActiveAwardData> mactiveAwardData
    {
      get { return _mactiveAwardData; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MMingGeIndex> _mingGeIndex = new global::System.Collections.Generic.List<com.protobuf.MMingGeIndex>();
    [global::ProtoBuf.ProtoMember(40, Name=@"mingGeIndex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MMingGeIndex> mingGeIndex
    {
      get { return _mingGeIndex; }
    }
  
    private string _loginBulletin = "";
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"loginBulletin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string loginBulletin
    {
      get { return _loginBulletin; }
      set { _loginBulletin = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MTask> _guideList = new global::System.Collections.Generic.List<com.protobuf.MTask>();
    [global::ProtoBuf.ProtoMember(42, Name=@"guideList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MTask> guideList
    {
      get { return _guideList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _plotList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(43, Name=@"plotList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> plotList
    {
      get { return _plotList; }
    }
  
    private int _isGMMail = default(int);
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"isGMMail", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isGMMail
    {
      get { return _isGMMail; }
      set { _isGMMail = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MYJiangLi> _mYJiangLi = new global::System.Collections.Generic.List<com.protobuf.MYJiangLi>();
    [global::ProtoBuf.ProtoMember(45, Name=@"mYJiangLi", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MYJiangLi> mYJiangLi
    {
      get { return _mYJiangLi; }
    }
  
    private long _qsNextTime = default(long);
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"qsNextTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long qsNextTime
    {
      get { return _qsNextTime; }
      set { _qsNextTime = value; }
    }
    private int _friendNum = default(int);
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"friendNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int friendNum
    {
      get { return _friendNum; }
      set { _friendNum = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cardIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(48, Name=@"cardIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cardIds
    {
      get { return _cardIds; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _equipIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(49, Name=@"equipIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> equipIds
    {
      get { return _equipIds; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _collectRewardIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(50, Name=@"collectRewardIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> collectRewardIds
    {
      get { return _collectRewardIds; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MGoodExchange> _exchangeList = new global::System.Collections.Generic.List<com.protobuf.MGoodExchange>();
    [global::ProtoBuf.ProtoMember(51, Name=@"exchangeList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MGoodExchange> exchangeList
    {
      get { return _exchangeList; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MMysteryShop> _mysteryShopList = new global::System.Collections.Generic.List<com.protobuf.MMysteryShop>();
    [global::ProtoBuf.ProtoMember(52, Name=@"mysteryShopList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MMysteryShop> mysteryShopList
    {
      get { return _mysteryShopList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _mingGeIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(53, Name=@"mingGeIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> mingGeIds
    {
      get { return _mingGeIds; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MInvest> _invests = new global::System.Collections.Generic.List<com.protobuf.MInvest>();
    [global::ProtoBuf.ProtoMember(54, Name=@"invests", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MInvest> invests
    {
      get { return _invests; }
    }
  
    private long _startServerWeekTime = default(long);
    [global::ProtoBuf.ProtoMember(55, IsRequired = false, Name=@"startServerWeekTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long startServerWeekTime
    {
      get { return _startServerWeekTime; }
      set { _startServerWeekTime = value; }
    }
    private com.protobuf.MQiSheng _qiSheng = null;
    [global::ProtoBuf.ProtoMember(56, IsRequired = false, Name=@"qiSheng", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MQiSheng qiSheng
    {
      get { return _qiSheng; }
      set { _qiSheng = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MBaGuaZhen> _baGuaZhen = new global::System.Collections.Generic.List<com.protobuf.MBaGuaZhen>();
    [global::ProtoBuf.ProtoMember(57, Name=@"baGuaZhen", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MBaGuaZhen> baGuaZhen
    {
      get { return _baGuaZhen; }
    }
  
    private com.protobuf.MTianGong _tianGong = null;
    [global::ProtoBuf.ProtoMember(58, IsRequired = false, Name=@"tianGong", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MTianGong tianGong
    {
      get { return _tianGong; }
      set { _tianGong = value; }
    }
    private com.protobuf.MSignIn _signIn = null;
    [global::ProtoBuf.ProtoMember(59, IsRequired = false, Name=@"signIn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MSignIn signIn
    {
      get { return _signIn; }
      set { _signIn = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_2_1")]
  public partial class Msg_2_1 : global::ProtoBuf.IExtensible
  {
    public Msg_2_1() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_2_1_")]
  public partial class Msg_2_1_ : global::ProtoBuf.IExtensible
  {
    public Msg_2_1_() {}
    
    private com.protobuf.MLoginData _loginData = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"loginData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MLoginData loginData
    {
      get { return _loginData; }
      set { _loginData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_2_2")]
  public partial class Msg_2_2 : global::ProtoBuf.IExtensible
  {
    public Msg_2_2() {}
    
    private string _aid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"aid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string aid
    {
      get { return _aid; }
      set { _aid = value; }
    }
    private string _platformId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"platformId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string platformId
    {
      get { return _platformId; }
      set { _platformId = value; }
    }
    private string _terminalType = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"terminalType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string terminalType
    {
      get { return _terminalType; }
      set { _terminalType = value; }
    }
    private string _openKey = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"openKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string openKey
    {
      get { return _openKey; }
      set { _openKey = value; }
    }
    private int _operator = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"operator", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int @operator
    {
      get { return _operator; }
      set { _operator = value; }
    }
    private int _zoneId = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"zoneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int zoneId
    {
      get { return _zoneId; }
      set { _zoneId = value; }
    }
    private int _reLogin = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"reLogin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reLogin
    {
      get { return _reLogin; }
      set { _reLogin = value; }
    }
    private string _pfkey = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"pfkey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pfkey
    {
      get { return _pfkey; }
      set { _pfkey = value; }
    }
    private string _pf = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"pf", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pf
    {
      get { return _pf; }
      set { _pf = value; }
    }
    private string _sessionId = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"sessionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sessionId
    {
      get { return _sessionId; }
      set { _sessionId = value; }
    }
    private string _sessionType = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"sessionType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sessionType
    {
      get { return _sessionType; }
      set { _sessionType = value; }
    }
    private string _uin = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uin
    {
      get { return _uin; }
      set { _uin = value; }
    }
    private string _clientVersion = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"clientVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clientVersion
    {
      get { return _clientVersion; }
      set { _clientVersion = value; }
    }
    private string _payToken = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"payToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string payToken
    {
      get { return _payToken; }
      set { _payToken = value; }
    }
    private string _ppToken = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"ppToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ppToken
    {
      get { return _ppToken; }
      set { _ppToken = value; }
    }
    private string _lingJingToken = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"lingJingToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string lingJingToken
    {
      get { return _lingJingToken; }
      set { _lingJingToken = value; }
    }
    private string _lingJingChannel = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"lingJingChannel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string lingJingChannel
    {
      get { return _lingJingChannel; }
      set { _lingJingChannel = value; }
    }
    private int _random = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"random", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int random
    {
      get { return _random; }
      set { _random = value; }
    }
    private string _loginSig = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"loginSig", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string loginSig
    {
      get { return _loginSig; }
      set { _loginSig = value; }
    }
    private int _loginTime = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"loginTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int loginTime
    {
      get { return _loginTime; }
      set { _loginTime = value; }
    }
    private string _sid = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_2_2_")]
  public partial class Msg_2_2_ : global::ProtoBuf.IExtensible
  {
    public Msg_2_2_() {}
    
    private int _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private com.protobuf.MLoginData _loginData = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"loginData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MLoginData loginData
    {
      get { return _loginData; }
      set { _loginData = value; }
    }
    private int _reLogin = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reLogin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reLogin
    {
      get { return _reLogin; }
      set { _reLogin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_2_3_")]
  public partial class Msg_2_3_ : global::ProtoBuf.IExtensible
  {
    public Msg_2_3_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_2_4")]
  public partial class Msg_2_4 : global::ProtoBuf.IExtensible
  {
    public Msg_2_4() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_2_5")]
  public partial class Msg_2_5 : global::ProtoBuf.IExtensible
  {
    public Msg_2_5() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}