//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: active.proto
// Note: requires additional types generated from: object.proto
namespace com.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MActiveGiftData")]
  public partial class MActiveGiftData : global::ProtoBuf.IExtensible
  {
    public MActiveGiftData() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MFirstRecharge> _firstRecharge = new global::System.Collections.Generic.List<com.protobuf.MFirstRecharge>();
    [global::ProtoBuf.ProtoMember(1, Name=@"firstRecharge", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MFirstRecharge> firstRecharge
    {
      get { return _firstRecharge; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MRechargeData> _rechargeData = new global::System.Collections.Generic.List<com.protobuf.MRechargeData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rechargeData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MRechargeData> rechargeData
    {
      get { return _rechargeData; }
    }
  
    private int _xianShiXYuanBao = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"xianShiXYuanBao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xianShiXYuanBao
    {
      get { return _xianShiXYuanBao; }
      set { _xianShiXYuanBao = value; }
    }
    private int _xianShiCYuanBao = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"xianShiCYuanBao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xianShiCYuanBao
    {
      get { return _xianShiCYuanBao; }
      set { _xianShiCYuanBao = value; }
    }
    private int _xianShiMoneyTreeCount = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"xianShiMoneyTreeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xianShiMoneyTreeCount
    {
      get { return _xianShiMoneyTreeCount; }
      set { _xianShiMoneyTreeCount = value; }
    }
    private int _xianZhiXianShiChongZhi = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"xianZhiXianShiChongZhi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xianZhiXianShiChongZhi
    {
      get { return _xianZhiXianShiChongZhi; }
      set { _xianZhiXianShiChongZhi = value; }
    }
    private int _xianZhiXianShiXiaoFei = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"xianZhiXianShiXiaoFei", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xianZhiXianShiXiaoFei
    {
      get { return _xianZhiXianShiXiaoFei; }
      set { _xianZhiXianShiXiaoFei = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MRechargeData")]
  public partial class MRechargeData : global::ProtoBuf.IExtensible
  {
    public MRechargeData() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _count = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private long _drowTime = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"drowTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long drowTime
    {
      get { return _drowTime; }
      set { _drowTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MFirstRecharge")]
  public partial class MFirstRecharge : global::ProtoBuf.IExtensible
  {
    public MFirstRecharge() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _yuanbao = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"yuanbao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int yuanbao
    {
      get { return _yuanbao; }
      set { _yuanbao = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MActiveData")]
  public partial class MActiveData : global::ProtoBuf.IExtensible
  {
    public MActiveData() {}
    
    private int _activeId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"activeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int activeId
    {
      get { return _activeId; }
      set { _activeId = value; }
    }
    private int _activeType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"activeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int activeType
    {
      get { return _activeType; }
      set { _activeType = value; }
    }
    private long _beginTime = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"beginTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long beginTime
    {
      get { return _beginTime; }
      set { _beginTime = value; }
    }
    private long _endTime = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private long _beginDrawTime = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"beginDrawTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long beginDrawTime
    {
      get { return _beginDrawTime; }
      set { _beginDrawTime = value; }
    }
    private long _endDrawTime = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"endDrawTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long endDrawTime
    {
      get { return _endDrawTime; }
      set { _endDrawTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MActiveAwardData")]
  public partial class MActiveAwardData : global::ProtoBuf.IExtensible
  {
    public MActiveAwardData() {}
    
    private int _awardId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"awardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int awardId
    {
      get { return _awardId; }
      set { _awardId = value; }
    }
    private int _drawNum = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"drawNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int drawNum
    {
      get { return _drawNum; }
      set { _drawNum = value; }
    }
    private int _grantNum = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"grantNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int grantNum
    {
      get { return _grantNum; }
      set { _grantNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_0_")]
  public partial class Msg_10_0_ : global::ProtoBuf.IExtensible
  {
    public Msg_10_0_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MActiveData> _activeData = new global::System.Collections.Generic.List<com.protobuf.MActiveData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"activeData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MActiveData> activeData
    {
      get { return _activeData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_1_")]
  public partial class Msg_10_1_ : global::ProtoBuf.IExtensible
  {
    public Msg_10_1_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MActiveAwardData> _mactiveAwardData = new global::System.Collections.Generic.List<com.protobuf.MActiveAwardData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mactiveAwardData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MActiveAwardData> mactiveAwardData
    {
      get { return _mactiveAwardData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_2")]
  public partial class Msg_10_2 : global::ProtoBuf.IExtensible
  {
    public Msg_10_2() {}
    
    private int _awardId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"awardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int awardId
    {
      get { return _awardId; }
      set { _awardId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_2_")]
  public partial class Msg_10_2_ : global::ProtoBuf.IExtensible
  {
    public Msg_10_2_() {}
    
    private int _awardId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"awardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int awardId
    {
      get { return _awardId; }
      set { _awardId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_4_")]
  public partial class Msg_10_4_ : global::ProtoBuf.IExtensible
  {
    public Msg_10_4_() {}
    
    private int _activeId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"activeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int activeId
    {
      get { return _activeId; }
      set { _activeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_7")]
  public partial class Msg_10_7 : global::ProtoBuf.IExtensible
  {
    public Msg_10_7() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_7_")]
  public partial class Msg_10_7_ : global::ProtoBuf.IExtensible
  {
    public Msg_10_7_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_8_")]
  public partial class Msg_10_8_ : global::ProtoBuf.IExtensible
  {
    public Msg_10_8_() {}
    
    private com.protobuf.MActiveGiftData _activeGiftData = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"activeGiftData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MActiveGiftData activeGiftData
    {
      get { return _activeGiftData; }
      set { _activeGiftData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_10")]
  public partial class Msg_10_10 : global::ProtoBuf.IExtensible
  {
    public Msg_10_10() {}
    
    private string _code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_10_")]
  public partial class Msg_10_10_ : global::ProtoBuf.IExtensible
  {
    public Msg_10_10_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MDropGood> _dropGood = new global::System.Collections.Generic.List<com.protobuf.MDropGood>();
    [global::ProtoBuf.ProtoMember(1, Name=@"dropGood", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MDropGood> dropGood
    {
      get { return _dropGood; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_11_")]
  public partial class Msg_10_11_ : global::ProtoBuf.IExtensible
  {
    public Msg_10_11_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MRankData> _rankData = new global::System.Collections.Generic.List<com.protobuf.MRankData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rankData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MRankData> rankData
    {
      get { return _rankData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MRankData")]
  public partial class MRankData : global::ProtoBuf.IExtensible
  {
    public MRankData() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _rank = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private int _yuanbao = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"yuanbao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int yuanbao
    {
      get { return _yuanbao; }
      set { _yuanbao = value; }
    }
    private int _zoneid = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"zoneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int zoneid
    {
      get { return _zoneid; }
      set { _zoneid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_12")]
  public partial class Msg_10_12 : global::ProtoBuf.IExtensible
  {
    public Msg_10_12() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_12_")]
  public partial class Msg_10_12_ : global::ProtoBuf.IExtensible
  {
    public Msg_10_12_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_13")]
  public partial class Msg_10_13 : global::ProtoBuf.IExtensible
  {
    public Msg_10_13() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_13_")]
  public partial class Msg_10_13_ : global::ProtoBuf.IExtensible
  {
    public Msg_10_13_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_10_14_")]
  public partial class Msg_10_14_ : global::ProtoBuf.IExtensible
  {
    public Msg_10_14_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MRankData> _rankData = new global::System.Collections.Generic.List<com.protobuf.MRankData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rankData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MRankData> rankData
    {
      get { return _rankData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}