//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: card.proto
// Note: requires additional types generated from: object.proto
// Note: requires additional types generated from: skill.proto
namespace com.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MCard")]
  public partial class MCard : global::ProtoBuf.IExtensible
  {
    public MCard() {}
    
    private int _cardId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private long _exp = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _color = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int color
    {
      get { return _color; }
      set { _color = value; }
    }
    private int _race = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"race", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int race
    {
      get { return _race; }
      set { _race = value; }
    }
    private int _xiangXing = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"xiangXing", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xiangXing
    {
      get { return _xiangXing; }
      set { _xiangXing = value; }
    }
    private int _starLevel = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"starLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int starLevel
    {
      get { return _starLevel; }
      set { _starLevel = value; }
    }
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _main = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"main", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int main
    {
      get { return _main; }
      set { _main = value; }
    }
    private int _location = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"location", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int location
    {
      get { return _location; }
      set { _location = value; }
    }
    private int _locking = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"locking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int locking
    {
      get { return _locking; }
      set { _locking = value; }
    }
    private int _ysId = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"ysId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ysId
    {
      get { return _ysId; }
      set { _ysId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MSkillGezi> _angerSkill = new global::System.Collections.Generic.List<com.protobuf.MSkillGezi>();
    [global::ProtoBuf.ProtoMember(17, Name=@"angerSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSkillGezi> angerSkill
    {
      get { return _angerSkill; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MSkillGezi> _talentSkill = new global::System.Collections.Generic.List<com.protobuf.MSkillGezi>();
    [global::ProtoBuf.ProtoMember(18, Name=@"talentSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSkillGezi> talentSkill
    {
      get { return _talentSkill; }
    }
  
    private int _strength = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private com.protobuf.MFightAttr _fightAttr = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"fightAttr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MFightAttr fightAttr
    {
      get { return _fightAttr; }
      set { _fightAttr = value; }
    }
    private int _fancyId = default(int);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"fancyId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fancyId
    {
      get { return _fancyId; }
      set { _fancyId = value; }
    }
    private int _angerSkillId = default(int);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"angerSkillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int angerSkillId
    {
      get { return _angerSkillId; }
      set { _angerSkillId = value; }
    }
    private int _sequence = default(int);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MSkillGezi> _tempAnger = new global::System.Collections.Generic.List<com.protobuf.MSkillGezi>();
    [global::ProtoBuf.ProtoMember(25, Name=@"tempAnger", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSkillGezi> tempAnger
    {
      get { return _tempAnger; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MSkillGezi> _tempTalent = new global::System.Collections.Generic.List<com.protobuf.MSkillGezi>();
    [global::ProtoBuf.ProtoMember(26, Name=@"tempTalent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSkillGezi> tempTalent
    {
      get { return _tempTalent; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MCardShard")]
  public partial class MCardShard : global::ProtoBuf.IExtensible
  {
    public MCardShard() {}
    
    private int _cardId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private int _number = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MBaiShen")]
  public partial class MBaiShen : global::ProtoBuf.IExtensible
  {
    public MBaiShen() {}
    
    private int _cardId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private long _exp = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MBaGuaZhen")]
  public partial class MBaGuaZhen : global::ProtoBuf.IExtensible
  {
    public MBaGuaZhen() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private com.protobuf.MBasicAttr _basicAttr = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"basicAttr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MBasicAttr basicAttr
    {
      get { return _basicAttr; }
      set { _basicAttr = value; }
    }
    private com.protobuf.MBasicAttr _tempBasicAttr = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"tempBasicAttr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MBasicAttr tempBasicAttr
    {
      get { return _tempBasicAttr; }
      set { _tempBasicAttr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_0_")]
  public partial class Msg_12_0_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_0_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MCardShard> _cardShard = new global::System.Collections.Generic.List<com.protobuf.MCardShard>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cardShard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MCardShard> cardShard
    {
      get { return _cardShard; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_1_")]
  public partial class Msg_12_1_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_1_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MCard> _cardData = new global::System.Collections.Generic.List<com.protobuf.MCard>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cardData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MCard> cardData
    {
      get { return _cardData; }
    }
  
    private int _tipRes = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tipRes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tipRes
    {
      get { return _tipRes; }
      set { _tipRes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_3_")]
  public partial class Msg_12_3_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_3_() {}
    
    private readonly global::System.Collections.Generic.List<long> _idList = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"idList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> idList
    {
      get { return _idList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_4")]
  public partial class Msg_12_4 : global::ProtoBuf.IExtensible
  {
    public Msg_12_4() {}
    
    private long _cardId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _idList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"idList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> idList
    {
      get { return _idList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_4_")]
  public partial class Msg_12_4_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_4_() {}
    
    private int _isBomb = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isBomb", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isBomb
    {
      get { return _isBomb; }
      set { _isBomb = value; }
    }
    private int _exp = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_5")]
  public partial class Msg_12_5 : global::ProtoBuf.IExtensible
  {
    public Msg_12_5() {}
    
    private long _cardId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_5_")]
  public partial class Msg_12_5_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_5_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_6")]
  public partial class Msg_12_6 : global::ProtoBuf.IExtensible
  {
    public Msg_12_6() {}
    
    private long _cardId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_6_")]
  public partial class Msg_12_6_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_6_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_8")]
  public partial class Msg_12_8 : global::ProtoBuf.IExtensible
  {
    public Msg_12_8() {}
    
    private long _cardId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_8_")]
  public partial class Msg_12_8_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_8_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_10")]
  public partial class Msg_12_10 : global::ProtoBuf.IExtensible
  {
    public Msg_12_10() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _number = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_10_")]
  public partial class Msg_12_10_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_10_() {}
    
    private int _bombCount = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bombCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bombCount
    {
      get { return _bombCount; }
      set { _bombCount = value; }
    }
    private com.protobuf.MBaiShen _baiShen = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"baiShen", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MBaiShen baiShen
    {
      get { return _baiShen; }
      set { _baiShen = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_11")]
  public partial class Msg_12_11 : global::ProtoBuf.IExtensible
  {
    public Msg_12_11() {}
    
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_11_")]
  public partial class Msg_12_11_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_11_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_12")]
  public partial class Msg_12_12 : global::ProtoBuf.IExtensible
  {
    public Msg_12_12() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_12_")]
  public partial class Msg_12_12_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_12_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_13")]
  public partial class Msg_12_13 : global::ProtoBuf.IExtensible
  {
    public Msg_12_13() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_12_13_")]
  public partial class Msg_12_13_ : global::ProtoBuf.IExtensible
  {
    public Msg_12_13_() {}
    
    private com.protobuf.MBaGuaZhen _baGuaZhen = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"baGuaZhen", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MBaGuaZhen baGuaZhen
    {
      get { return _baGuaZhen; }
      set { _baGuaZhen = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}