//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: compete.proto
namespace com.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MCompeteRole")]
  public partial class MCompeteRole : global::ProtoBuf.IExtensible
  {
    public MCompeteRole() {}
    
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _targetName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string targetName
    {
      get { return _targetName; }
      set { _targetName = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _cardId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private int _order = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int order
    {
      get { return _order; }
      set { _order = value; }
    }
    private int _starLevel = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"starLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int starLevel
    {
      get { return _starLevel; }
      set { _starLevel = value; }
    }
    private int _color = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int color
    {
      get { return _color; }
      set { _color = value; }
    }
    private int _strength = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MCompeteData")]
  public partial class MCompeteData : global::ProtoBuf.IExtensible
  {
    public MCompeteData() {}
    
    private int _score = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _order = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int order
    {
      get { return _order; }
      set { _order = value; }
    }
    private int _orderReward = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"orderReward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int orderReward
    {
      get { return _orderReward; }
      set { _orderReward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_9_1_")]
  public partial class Msg_9_1_ : global::ProtoBuf.IExtensible
  {
    public Msg_9_1_() {}
    
    private com.protobuf.MCompeteData _competeData = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"competeData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MCompeteData competeData
    {
      get { return _competeData; }
      set { _competeData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_9_2")]
  public partial class Msg_9_2 : global::ProtoBuf.IExtensible
  {
    public Msg_9_2() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_9_2_")]
  public partial class Msg_9_2_ : global::ProtoBuf.IExtensible
  {
    public Msg_9_2_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MCompeteRole> _competeRoleList = new global::System.Collections.Generic.List<com.protobuf.MCompeteRole>();
    [global::ProtoBuf.ProtoMember(1, Name=@"competeRoleList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MCompeteRole> competeRoleList
    {
      get { return _competeRoleList; }
    }
  
    private com.protobuf.MCompeteData _competeData = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"competeData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MCompeteData competeData
    {
      get { return _competeData; }
      set { _competeData = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _scoreRewardList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"scoreRewardList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> scoreRewardList
    {
      get { return _scoreRewardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_9_3")]
  public partial class Msg_9_3 : global::ProtoBuf.IExtensible
  {
    public Msg_9_3() {}
    
    private int _order = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int order
    {
      get { return _order; }
      set { _order = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_9_3_")]
  public partial class Msg_9_3_ : global::ProtoBuf.IExtensible
  {
    public Msg_9_3_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_9_4")]
  public partial class Msg_9_4 : global::ProtoBuf.IExtensible
  {
    public Msg_9_4() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_9_4_")]
  public partial class Msg_9_4_ : global::ProtoBuf.IExtensible
  {
    public Msg_9_4_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_9_5")]
  public partial class Msg_9_5 : global::ProtoBuf.IExtensible
  {
    public Msg_9_5() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_9_5_")]
  public partial class Msg_9_5_ : global::ProtoBuf.IExtensible
  {
    public Msg_9_5_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_9_6")]
  public partial class Msg_9_6 : global::ProtoBuf.IExtensible
  {
    public Msg_9_6() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _number = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_9_6_")]
  public partial class Msg_9_6_ : global::ProtoBuf.IExtensible
  {
    public Msg_9_6_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_9_8_")]
  public partial class Msg_9_8_ : global::ProtoBuf.IExtensible
  {
    public Msg_9_8_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MCompeteRole> _competeRoleList = new global::System.Collections.Generic.List<com.protobuf.MCompeteRole>();
    [global::ProtoBuf.ProtoMember(1, Name=@"competeRoleList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MCompeteRole> competeRoleList
    {
      get { return _competeRoleList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_9_10")]
  public partial class Msg_9_10 : global::ProtoBuf.IExtensible
  {
    public Msg_9_10() {}
    
    private int _page = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int page
    {
      get { return _page; }
      set { _page = value; }
    }
    private int _pageSize = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pageSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pageSize
    {
      get { return _pageSize; }
      set { _pageSize = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_9_10_")]
  public partial class Msg_9_10_ : global::ProtoBuf.IExtensible
  {
    public Msg_9_10_() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MCompeteRole> _orderList = new global::System.Collections.Generic.List<com.protobuf.MCompeteRole>();
    [global::ProtoBuf.ProtoMember(1, Name=@"orderList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MCompeteRole> orderList
    {
      get { return _orderList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}