//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: gangWar.proto
namespace com.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MWarGang")]
  public partial class MWarGang : global::ProtoBuf.IExtensible
  {
    public MWarGang() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _gangLevel = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gangLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gangLevel
    {
      get { return _gangLevel; }
      set { _gangLevel = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MWarDevil> _warDevilList = new global::System.Collections.Generic.List<com.protobuf.MWarDevil>();
    [global::ProtoBuf.ProtoMember(3, Name=@"warDevilList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MWarDevil> warDevilList
    {
      get { return _warDevilList; }
    }
  
    private long _endTime = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MWarMember> _warMemberList = new global::System.Collections.Generic.List<com.protobuf.MWarMember>();
    [global::ProtoBuf.ProtoMember(5, Name=@"warMemberList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MWarMember> warMemberList
    {
      get { return _warMemberList; }
    }
  
    private int _gangScore = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gangScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gangScore
    {
      get { return _gangScore; }
      set { _gangScore = value; }
    }
    private int _enemyScore = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"enemyScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int enemyScore
    {
      get { return _enemyScore; }
      set { _enemyScore = value; }
    }
    private int _standardScore = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"standardScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int standardScore
    {
      get { return _standardScore; }
      set { _standardScore = value; }
    }
    private int _challengedCount = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"challengedCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int challengedCount
    {
      get { return _challengedCount; }
      set { _challengedCount = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MWarLog> _logList = new global::System.Collections.Generic.List<com.protobuf.MWarLog>();
    [global::ProtoBuf.ProtoMember(10, Name=@"logList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MWarLog> logList
    {
      get { return _logList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MWarDevil")]
  public partial class MWarDevil : global::ProtoBuf.IExtensible
  {
    public MWarDevil() {}
    
    private int _uniqueId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _leftHp = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"leftHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int leftHp
    {
      get { return _leftHp; }
      set { _leftHp = value; }
    }
    private int _totalHp = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"totalHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalHp
    {
      get { return _totalHp; }
      set { _totalHp = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private string _killer = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"killer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string killer
    {
      get { return _killer; }
      set { _killer = value; }
    }
    private string _attacker = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"attacker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string attacker
    {
      get { return _attacker; }
      set { _attacker = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _cardId = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private int _color = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int color
    {
      get { return _color; }
      set { _color = value; }
    }
    private int _strength = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MWarMember")]
  public partial class MWarMember : global::ProtoBuf.IExtensible
  {
    public MWarMember() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _cardId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private int _challangeCount = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"challangeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int challangeCount
    {
      get { return _challangeCount; }
      set { _challangeCount = value; }
    }
    private int _buyChallengeCount = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"buyChallengeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buyChallengeCount
    {
      get { return _buyChallengeCount; }
      set { _buyChallengeCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MWarLog")]
  public partial class MWarLog : global::ProtoBuf.IExtensible
  {
    public MWarLog() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _color = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int color
    {
      get { return _color; }
      set { _color = value; }
    }
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private string _enemyName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"enemyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string enemyName
    {
      get { return _enemyName; }
      set { _enemyName = value; }
    }
    private int _enemyColor = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"enemyColor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int enemyColor
    {
      get { return _enemyColor; }
      set { _enemyColor = value; }
    }
    private long _time = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_34_1")]
  public partial class Msg_34_1 : global::ProtoBuf.IExtensible
  {
    public Msg_34_1() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_34_2_")]
  public partial class Msg_34_2_ : global::ProtoBuf.IExtensible
  {
    public Msg_34_2_() {}
    
    private com.protobuf.MWarGang _warGang = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"warGang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MWarGang warGang
    {
      get { return _warGang; }
      set { _warGang = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_34_3_")]
  public partial class Msg_34_3_ : global::ProtoBuf.IExtensible
  {
    public Msg_34_3_() {}
    
    private com.protobuf.MWarDevil _warDevil = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"warDevil", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MWarDevil warDevil
    {
      get { return _warDevil; }
      set { _warDevil = value; }
    }
    private int _gangScore = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gangScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gangScore
    {
      get { return _gangScore; }
      set { _gangScore = value; }
    }
    private int _challengedCount = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"challengedCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int challengedCount
    {
      get { return _challengedCount; }
      set { _challengedCount = value; }
    }
    private com.protobuf.MWarLog _warLog = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"warLog", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MWarLog warLog
    {
      get { return _warLog; }
      set { _warLog = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_34_4_")]
  public partial class Msg_34_4_ : global::ProtoBuf.IExtensible
  {
    public Msg_34_4_() {}
    
    private com.protobuf.MWarGang _warGang = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"warGang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MWarGang warGang
    {
      get { return _warGang; }
      set { _warGang = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_34_5")]
  public partial class Msg_34_5 : global::ProtoBuf.IExtensible
  {
    public Msg_34_5() {}
    
    private int _uniqueId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_34_5_")]
  public partial class Msg_34_5_ : global::ProtoBuf.IExtensible
  {
    public Msg_34_5_() {}
    
    private int _challengeCount = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"challengeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int challengeCount
    {
      get { return _challengeCount; }
      set { _challengeCount = value; }
    }
    private int _buyChallengeCount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buyChallengeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buyChallengeCount
    {
      get { return _buyChallengeCount; }
      set { _buyChallengeCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_34_6")]
  public partial class Msg_34_6 : global::ProtoBuf.IExtensible
  {
    public Msg_34_6() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_34_6_")]
  public partial class Msg_34_6_ : global::ProtoBuf.IExtensible
  {
    public Msg_34_6_() {}
    
    private int _warReward = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"warReward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int warReward
    {
      get { return _warReward; }
      set { _warReward = value; }
    }
    private int _rewardId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rewardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rewardId
    {
      get { return _rewardId; }
      set { _rewardId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_34_7_")]
  public partial class Msg_34_7_ : global::ProtoBuf.IExtensible
  {
    public Msg_34_7_() {}
    
    private int _enemyScore = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"enemyScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int enemyScore
    {
      get { return _enemyScore; }
      set { _enemyScore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_34_8_")]
  public partial class Msg_34_8_ : global::ProtoBuf.IExtensible
  {
    public Msg_34_8_() {}
    
    private int _warReward = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"warReward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int warReward
    {
      get { return _warReward; }
      set { _warReward = value; }
    }
    private int _warStatus = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"warStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int warStatus
    {
      get { return _warStatus; }
      set { _warStatus = value; }
    }
    private int _warResult = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"warResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int warResult
    {
      get { return _warResult; }
      set { _warResult = value; }
    }
    private int _winCount = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"winCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winCount
    {
      get { return _winCount; }
      set { _winCount = value; }
    }
    private int _loseCount = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"loseCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int loseCount
    {
      get { return _loseCount; }
      set { _loseCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}