//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: role.proto
// Note: requires additional types generated from: object.proto
// Note: requires additional types generated from: card.proto
// Note: requires additional types generated from: pet.proto
// Note: requires additional types generated from: horse.proto
// Note: requires additional types generated from: equip.proto
namespace com.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MRoleData")]
  public partial class MRoleData : global::ProtoBuf.IExtensible
  {
    public MRoleData() {}
    
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _strength = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MCard> _card = new global::System.Collections.Generic.List<com.protobuf.MCard>();
    [global::ProtoBuf.ProtoMember(5, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MCard> card
    {
      get { return _card; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MEquip> _equip = new global::System.Collections.Generic.List<com.protobuf.MEquip>();
    [global::ProtoBuf.ProtoMember(6, Name=@"equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MEquip> equip
    {
      get { return _equip; }
    }
  
    private com.protobuf.MPet _pet = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"pet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MPet pet
    {
      get { return _pet; }
      set { _pet = value; }
    }
    private com.protobuf.MHorse _horse = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"horse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MHorse horse
    {
      get { return _horse; }
      set { _horse = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MRoleReward")]
  public partial class MRoleReward : global::ProtoBuf.IExtensible
  {
    public MRoleReward() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _rewardId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rewardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rewardId
    {
      get { return _rewardId; }
      set { _rewardId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.protobuf.MDropGood> _rewardList = new global::System.Collections.Generic.List<com.protobuf.MDropGood>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rewardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MDropGood> rewardList
    {
      get { return _rewardList; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _paramValues = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"paramValues", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> paramValues
    {
      get { return _paramValues; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MRoleCard")]
  public partial class MRoleCard : global::ProtoBuf.IExtensible
  {
    public MRoleCard() {}
    
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _color = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int color
    {
      get { return _color; }
      set { _color = value; }
    }
    private int _race = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"race", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int race
    {
      get { return _race; }
      set { _race = value; }
    }
    private int _xiangXing = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"xiangXing", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xiangXing
    {
      get { return _xiangXing; }
      set { _xiangXing = value; }
    }
    private int _starLevel = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"starLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int starLevel
    {
      get { return _starLevel; }
      set { _starLevel = value; }
    }
    private int _cardId = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private int _strength = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MRole")]
  public partial class MRole : global::ProtoBuf.IExtensible
  {
    public MRole() {}
    
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _online = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int online
    {
      get { return _online; }
      set { _online = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _strength = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private int _silver = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"silver", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int silver
    {
      get { return _silver; }
      set { _silver = value; }
    }
    private int _yuanBao = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"yuanBao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int yuanBao
    {
      get { return _yuanBao; }
      set { _yuanBao = value; }
    }
    private int _chargeYuanbao = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"chargeYuanbao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chargeYuanbao
    {
      get { return _chargeYuanbao; }
      set { _chargeYuanbao = value; }
    }
    private int _magicLevel = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"magicLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int magicLevel
    {
      get { return _magicLevel; }
      set { _magicLevel = value; }
    }
    private int _magicStatus = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"magicStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int magicStatus
    {
      get { return _magicStatus; }
      set { _magicStatus = value; }
    }
    private string _friendCode = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"friendCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string friendCode
    {
      get { return _friendCode; }
      set { _friendCode = value; }
    }
    private int _tiLi = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"tiLi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tiLi
    {
      get { return _tiLi; }
      set { _tiLi = value; }
    }
    private com.protobuf.MRoleDairy _roleDairy = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"roleDairy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MRoleDairy roleDairy
    {
      get { return _roleDairy; }
      set { _roleDairy = value; }
    }
    private int _friendPoint = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"friendPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int friendPoint
    {
      get { return _friendPoint; }
      set { _friendPoint = value; }
    }
    private int _vipLevel = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"vipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vipLevel
    {
      get { return _vipLevel; }
      set { _vipLevel = value; }
    }
    private long _createTime = default(long);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private int _gangContribute = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"gangContribute", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gangContribute
    {
      get { return _gangContribute; }
      set { _gangContribute = value; }
    }
    private int _daMingZhou = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"daMingZhou", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int daMingZhou
    {
      get { return _daMingZhou; }
      set { _daMingZhou = value; }
    }
    private int _loginCount = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"loginCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int loginCount
    {
      get { return _loginCount; }
      set { _loginCount = value; }
    }
    private int _zoneId = default(int);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"zoneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int zoneId
    {
      get { return _zoneId; }
      set { _zoneId = value; }
    }
    private long _tiLiTime = default(long);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"tiLiTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tiLiTime
    {
      get { return _tiLiTime; }
      set { _tiLiTime = value; }
    }
    private string _openid = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"openid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string openid
    {
      get { return _openid; }
      set { _openid = value; }
    }
    private int _shengWan = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"shengWan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int shengWan
    {
      get { return _shengWan; }
      set { _shengWan = value; }
    }
    private int _useStar = default(int);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"useStar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int useStar
    {
      get { return _useStar; }
      set { _useStar = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MRoleDairy")]
  public partial class MRoleDairy : global::ProtoBuf.IExtensible
  {
    public MRoleDairy() {}
    
    private int _competeCount = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"competeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int competeCount
    {
      get { return _competeCount; }
      set { _competeCount = value; }
    }
    private int _buyCompeteCount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buyCompeteCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buyCompeteCount
    {
      get { return _buyCompeteCount; }
      set { _buyCompeteCount = value; }
    }
    private int _moShenCount = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"moShenCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int moShenCount
    {
      get { return _moShenCount; }
      set { _moShenCount = value; }
    }
    private int _buyMoShenCount = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"buyMoShenCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buyMoShenCount
    {
      get { return _buyMoShenCount; }
      set { _buyMoShenCount = value; }
    }
    private int _zhaohunNum = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"zhaohunNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int zhaohunNum
    {
      get { return _zhaohunNum; }
      set { _zhaohunNum = value; }
    }
    private int _buyTiLiCount = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"buyTiLiCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buyTiLiCount
    {
      get { return _buyTiLiCount; }
      set { _buyTiLiCount = value; }
    }
    private int _contendBookCount = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"contendBookCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int contendBookCount
    {
      get { return _contendBookCount; }
      set { _contendBookCount = value; }
    }
    private int _guaGuaLeCount = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"guaGuaLeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guaGuaLeCount
    {
      get { return _guaGuaLeCount; }
      set { _guaGuaLeCount = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _tiLiRewardList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"tiLiRewardList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> tiLiRewardList
    {
      get { return _tiLiRewardList; }
    }
  
    private int _checkIn = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"checkIn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int checkIn
    {
      get { return _checkIn; }
      set { _checkIn = value; }
    }
    private int _contestCount = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"contestCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int contestCount
    {
      get { return _contestCount; }
      set { _contestCount = value; }
    }
    private int _feedHorseCount = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"feedHorseCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int feedHorseCount
    {
      get { return _feedHorseCount; }
      set { _feedHorseCount = value; }
    }
    private int _gangHellCount = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"gangHellCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gangHellCount
    {
      get { return _gangHellCount; }
      set { _gangHellCount = value; }
    }
    private int _gangHellBuyCount = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"gangHellBuyCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gangHellBuyCount
    {
      get { return _gangHellBuyCount; }
      set { _gangHellBuyCount = value; }
    }
    private int _gangWarCount = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"gangWarCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gangWarCount
    {
      get { return _gangWarCount; }
      set { _gangWarCount = value; }
    }
    private int _tianGongCount = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"tianGongCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tianGongCount
    {
      get { return _tianGongCount; }
      set { _tianGongCount = value; }
    }
    private int _qiShengCount = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"qiShengCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int qiShengCount
    {
      get { return _qiShengCount; }
      set { _qiShengCount = value; }
    }
    private int _buyBookCount = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"buyBookCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buyBookCount
    {
      get { return _buyBookCount; }
      set { _buyBookCount = value; }
    }
    private int _buyZhaohunNum = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"buyZhaohunNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buyZhaohunNum
    {
      get { return _buyZhaohunNum; }
      set { _buyZhaohunNum = value; }
    }
    private int _gangFuliCount = default(int);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"gangFuliCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gangFuliCount
    {
      get { return _gangFuliCount; }
      set { _gangFuliCount = value; }
    }
    private int _receiveFriendTiLi = default(int);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"receiveFriendTiLi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int receiveFriendTiLi
    {
      get { return _receiveFriendTiLi; }
      set { _receiveFriendTiLi = value; }
    }
    private int _sentTili = default(int);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"sentTili", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sentTili
    {
      get { return _sentTili; }
      set { _sentTili = value; }
    }
    private int _buyTianGongCount = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"buyTianGongCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buyTianGongCount
    {
      get { return _buyTianGongCount; }
      set { _buyTianGongCount = value; }
    }
    private int _qiuShenNum = default(int);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"qiuShenNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int qiuShenNum
    {
      get { return _qiuShenNum; }
      set { _qiuShenNum = value; }
    }
    private int _signInToday = default(int);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"signInToday", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int signInToday
    {
      get { return _signInToday; }
      set { _signInToday = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_1")]
  public partial class Msg_3_1 : global::ProtoBuf.IExtensible
  {
    public Msg_3_1() {}
    
    private long _targetId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private string _targetName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string targetName
    {
      get { return _targetName; }
      set { _targetName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_1_")]
  public partial class Msg_3_1_ : global::ProtoBuf.IExtensible
  {
    public Msg_3_1_() {}
    
    private com.protobuf.MRoleCard _target = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MRoleCard target
    {
      get { return _target; }
      set { _target = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_2_")]
  public partial class Msg_3_2_ : global::ProtoBuf.IExtensible
  {
    public Msg_3_2_() {}
    
    private com.protobuf.MRole _role = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MRole role
    {
      get { return _role; }
      set { _role = value; }
    }
    private long _rewardExp = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rewardExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long rewardExp
    {
      get { return _rewardExp; }
      set { _rewardExp = value; }
    }
    private int _tip = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tip
    {
      get { return _tip; }
      set { _tip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_4_")]
  public partial class Msg_3_4_ : global::ProtoBuf.IExtensible
  {
    public Msg_3_4_() {}
    
    private com.protobuf.MRoleReward _reward = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MRoleReward reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_5")]
  public partial class Msg_3_5 : global::ProtoBuf.IExtensible
  {
    public Msg_3_5() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_5_")]
  public partial class Msg_3_5_ : global::ProtoBuf.IExtensible
  {
    public Msg_3_5_() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_6")]
  public partial class Msg_3_6 : global::ProtoBuf.IExtensible
  {
    public Msg_3_6() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_6_")]
  public partial class Msg_3_6_ : global::ProtoBuf.IExtensible
  {
    public Msg_3_6_() {}
    
    private readonly global::System.Collections.Generic.List<int> _idList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"idList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> idList
    {
      get { return _idList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_7")]
  public partial class Msg_3_7 : global::ProtoBuf.IExtensible
  {
    public Msg_3_7() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_7_")]
  public partial class Msg_3_7_ : global::ProtoBuf.IExtensible
  {
    public Msg_3_7_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_8")]
  public partial class Msg_3_8 : global::ProtoBuf.IExtensible
  {
    public Msg_3_8() {}
    
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_8_")]
  public partial class Msg_3_8_ : global::ProtoBuf.IExtensible
  {
    public Msg_3_8_() {}
    
    private com.protobuf.MRoleData _roleData = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MRoleData roleData
    {
      get { return _roleData; }
      set { _roleData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_3_9_")]
  public partial class Msg_3_9_ : global::ProtoBuf.IExtensible
  {
    public Msg_3_9_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}