//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: skill.proto
namespace com.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSkillGezi")]
  public partial class MSkillGezi : global::ProtoBuf.IExtensible
  {
    public MSkillGezi() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _skillId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSkill")]
  public partial class MSkill : global::ProtoBuf.IExtensible
  {
    public MSkill() {}
    
    private readonly global::System.Collections.Generic.List<com.protobuf.MSkillGezi> _angerSkill = new global::System.Collections.Generic.List<com.protobuf.MSkillGezi>();
    [global::ProtoBuf.ProtoMember(1, Name=@"angerSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSkillGezi> angerSkill
    {
      get { return _angerSkill; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MSkillGezi> _talentSkill = new global::System.Collections.Generic.List<com.protobuf.MSkillGezi>();
    [global::ProtoBuf.ProtoMember(2, Name=@"talentSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSkillGezi> talentSkill
    {
      get { return _talentSkill; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MSkillGezi> _tempAnger = new global::System.Collections.Generic.List<com.protobuf.MSkillGezi>();
    [global::ProtoBuf.ProtoMember(4, Name=@"tempAnger", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSkillGezi> tempAnger
    {
      get { return _tempAnger; }
    }
  
    private readonly global::System.Collections.Generic.List<com.protobuf.MSkillGezi> _tempTalent = new global::System.Collections.Generic.List<com.protobuf.MSkillGezi>();
    [global::ProtoBuf.ProtoMember(5, Name=@"tempTalent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.protobuf.MSkillGezi> tempTalent
    {
      get { return _tempTalent; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_14_0_")]
  public partial class Msg_14_0_ : global::ProtoBuf.IExtensible
  {
    public Msg_14_0_() {}
    
    private com.protobuf.MSkill _skill = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.protobuf.MSkill skill
    {
      get { return _skill; }
      set { _skill = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_14_1")]
  public partial class Msg_14_1 : global::ProtoBuf.IExtensible
  {
    public Msg_14_1() {}
    
    private long _cardId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private int _skillId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private int _count = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_14_1_")]
  public partial class Msg_14_1_ : global::ProtoBuf.IExtensible
  {
    public Msg_14_1_() {}
    
    private int _success = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_14_2")]
  public partial class Msg_14_2 : global::ProtoBuf.IExtensible
  {
    public Msg_14_2() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_14_2_")]
  public partial class Msg_14_2_ : global::ProtoBuf.IExtensible
  {
    public Msg_14_2_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_14_3")]
  public partial class Msg_14_3 : global::ProtoBuf.IExtensible
  {
    public Msg_14_3() {}
    
    private int _skillId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_14_3_")]
  public partial class Msg_14_3_ : global::ProtoBuf.IExtensible
  {
    public Msg_14_3_() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_14_4")]
  public partial class Msg_14_4 : global::ProtoBuf.IExtensible
  {
    public Msg_14_4() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_14_4_")]
  public partial class Msg_14_4_ : global::ProtoBuf.IExtensible
  {
    public Msg_14_4_() {}
    
    private int _skillId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}